version: "3.9"
services:
  redis:
    container_name: online-admittance-api-redis
    image: redis/redis-stack
    ports:
      - 6379:6379
      - 82:8001
    volumes:
      - online-admittance-api_redis-data:/data
  database:
    container_name: online-admittance-api-db
    image: postgres:16
    environment:
      POSTGRES_DB: online-admittance
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: online-admittance-api
    volumes:
      - online-admittance-api_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  minio:
    container_name: online-admittance-api-minio
    image: minio/minio
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: server --console-address ":9000" --address ":9001" /data
    volumes:
      - online-admittance-api_minio-data:/data
    expose:
      - 9001
    ports:
      - 83:9000
      - 84:9001

  minio-client:
    container_name: online-admittance-api-minio-bucket
    image: minio/mc
    restart: on-failure
    depends_on:
      - minio
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY}
      MINIO_BUCKET: ${AWS_BUCKET}
    entrypoint: >
      /bin/sh -c "
      curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o wait-for-it.sh;
      chmod +x wait-for-it.sh;
      ./wait-for-it.sh minio:9001;
      /usr/bin/mc config host add local http://minio:9001 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY};
      /usr/bin/mc rm -r --force local/$${MINIO_BUCKET};
      /usr/bin/mc mb local/$${MINIO_BUCKET};
      /usr/bin/mc policy set public local/$${MINIO_BUCKET};
      exit 0;"

volumes:
  online-admittance-api_postgres:
  online-admittance-api_minio-data:
  online-admittance-api_redis-data:

networks:
  default:
    name: online-admittance-api-network
